# -*- coding: utf-8 -*-
"""Skalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BTvDI0_aaALO9fxxURW73TwylueySi6
"""

x = 10

print(f"Tipe data x: {type(x)}")

y = 5

print(f"Tipe data y: {type(y)}")

hasil_tambah = x + y
print(f"Hasil x + y = {hasil_tambah}")

x_float = 12.5

hasil_float_y = x_float + y
print(f"Hasil x_float + y = {hasil_float_y}")

print(f"Tipe data x_float: {type(x_float)}")