# -*- coding: utf-8 -*-
"""TUGAS KODING SKALARS 3 PyTorch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxe896J0gsUYXrVLiLFpj7T8p_5dfJE2
"""



import torch

x_pt = torch.tensor(10)
print(f"x_pt: {x_pt.item()}")

print(f"Tipe data x: {x_pt.dtype}")

y_pt = torch.tensor(5)
print(f"y_pt: {y_pt.item()}")

print(f"Tipe data y: {y_pt.dtype}")

hasil_tambah_pt = x_pt + y_pt
print(f"Hasil x + y = {hasil_tambah_pt.item()}")

x_float_pt = torch.tensor(12.5)

hasil_float_pt = x_float_pt + y_pt
print(f"Hasil x_float + y = {hasil_float_pt.item()}")

print(f"Tipe data x_float: {x_float_pt.dtype}")

