# -*- coding: utf-8 -*-
"""TUGAS KODING SKALARS 2 TensorFlow

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqsYcoaty-qLFMlBm0nlUla6qNGtEMvB
"""

import tensorflow as tf

x_tf = tf.Variable(25, dtype=tf.int16)
print(f"x_tf: {x_tf.numpy()}")

print(f"Tipe data x_tf: {x_tf.dtype}")

y_tf = tf.Variable(3, dtype=tf.int16)
print(f"y_tf: {y_tf.numpy()}")

print(f"Tipe data y_tf: {y_tf.dtype}")

hasil_tf = x_tf + y_tf
print(f"Hasil x + y: {hasil_tf.numpy()}")

x_float_tf = tf.Variable(12.5, dtype=tf.float16)

hasil_float_tf = x_float_tf + tf.cast(y_tf, tf.float16)
print(f"Hasil x_float + y: {hasil_float_tf.numpy()}")